### ISSUE TITLE
A problem of the reranker dataset preprocessing

### ISSUE THREAD

**Issue by aaafc** [Zhilin123/personal_attributes#2] opened 2022-08-03 08:16 UTC
Hi @Zhilin123 , 
I'm currently working on personal attribute extraction as well, and this work inspires me a lot. 
I've tried to reproducing the experiments, and I've got an evaluation result of 13% (f1-score) higher than the produced result,  which confused me. 
I've tried to find the reason, and I've found a problem that might decrease the actual performance of the Reranker, which also increases the performance shown.

Firstly, at 

> https://github.com/Zhilin123/personal_attributes/blob/d18bffe02a3452f1390aeaf67b04c706228eb9c2/model/reranker_dataset.py#L44

, the ground dict added "[CLS]" and "[PAD]" tokens handcraftly, while at 

> https://github.com/Zhilin123/personal_attributes/blob/d18bffe02a3452f1390aeaf67b04c706228eb9c2/model/reranker_dataset.py#L51

The ground dict added special tokens again for there is no passing parameter "add_special_tokens = False"; this will make the ground ids looks like:
`[CLS] [CLS] token_1 token_2 ...[HEAD] head_tok [RELN] reln_tok [TAIL] tail_tok [PAD] [PAD]`

Secondly, at 

> https://github.com/Zhilin123/personal_attributes/blob/d18bffe02a3452f1390aeaf67b04c706228eb9c2/model/reranker_dataset.py#L64

The predicted dict added "[CLS]" and "[PAD]" tokens handcraftly as well, while at 

> https://github.com/Zhilin123/personal_attributes/blob/d18bffe02a3452f1390aeaf67b04c706228eb9c2/model/reranker_dataset.py#L71

The predicted dict does not added special tokens again; thus, the predicted dict looks like:
`[CLS] token_1 token_2 ...[HEAD] head_tok [RELN] reln_tok [TAIL] tail_tok [PAD]`

> https://github.com/Zhilin123/personal_attributes/blob/d18bffe02a3452f1390aeaf67b04c706228eb9c2/model/reranker_dataset.py#L70

shows that while the dataset uses cache for converting ids, once the predicted dict is identical with corresponding ground dict, the predicted ids will straightly copied the ground ids from the first step, which is also labeled as "1"; while the predicted ids which are labeld as "0", are converted at the second step, thus, 

For each sample labeled as 1, the ids looks like:
`[CLS] [CLS] token_1 token_2 ...[HEAD] head_tok [RELN] reln_tok [TAIL] tail_tok [PAD] [PAD]`
while for each sample labeld as 0, the ids looks like:
`[CLS] token_1 token_2 ...[HEAD] head_tok [RELN] reln_tok [TAIL] tail_tok [PAD]`

Thus, the Bert Reranker will directly seperated the samples with label "1" and "0", while it actually does not learned the semantic information from the triplets and sentences, but more likely from the count of [CLS] tokens. As a result, the ReRanker does not work during the prediction, and the final evaluation result becomes how many samples does the Generator successfully generate the correct triplets during the first K (K = 10) candidates, which results in the unusual result gain.

**Comment by Zhilin123** [comment] 2022-08-04 04:12
Thanks for raising this bug! The line `add_special_tokens=False` might have been accidentally deleted when cleaning up the code. I have now fixed this issue with the most recent commit. I will close this issue but feel free to open another one if you have further questions or issues that you encounter

**Closed as completed by Zhilin123** 2022-08-04 04:12 UTC

**Comment by aaafc** [comment] 2022-08-04 08:02
Thanks for the reply. 

I'm really grateful for you to reply the issue and fix the code so quickly, but this problem might has bigger influence than just adding additional [CLS] token.

During my experiment, after fixing the problem, the ReRanker with a single BERT encoder and a classification head layer hardly learns the differences between truth triplets and plausible triplets. 

I guess the reason is because the input sentences, which converted by those triplets, have little differences but one (or probably more than one) token with similar semantic features. Since BERT Encoder learns the vector for a sentence by its semantic features, it probably cannot differ those input sentences only by one pair of different (but probably similar) tokens.

The problem is, before fixing the problem, the BERT Encoder could easily learn the differences, since those input sentences has various counts of special token [CLS], which gives the ReRanker a nearly 100% of accuracy in seperating those ground triplets and plausible triplets (since the dev and test dataset uses the same preprocessing workflow).

The original accuracy of the information extraction is calculated by the overall pipeline with a Generator and a ReRanker, and with the ReRanker actually gets a 100% accuracy in evaluation process (which actually not that accurate in real scenes), the final evaluation result is not accurate, I think that goes to the probability of how many candidate groups includes the ground truth triplets after the generation process of the Generator.

As a result, it might have to retrain the ReRanker and re-evaluate the pipeline after fixing the problem. I'm not pretty sure the actual performances after the modification, but I think it will only have little performance gain over single Generator extractor.

**Comment by Zhilin123** [comment] 2022-08-06 05:53
I have repeated the experiment and confirmed that the Generator + Reranker setup has much performance gain (similar to what was reported in the paper) over the Generator only. I think the reason for this is that even though there is only the difference of one token (in many cases, this will be more), it is still able to tell the difference as the many examples used for training will help it to learn to be highly discriminative between very similar predicted triples, similar to using hard negatives for other forms of ML. For reproducibility, I used `bash train.sh .. extraction 43` for the Generator + Reranker and after that, `python model/generator_model.py --load_trained_model True --debug_mode False --config_name .. --mode head_reln_tail --data_subset within_sentence --inference_only True --generation_name original_spans+top-1 --generate_test True --random_seed 43 ` for the Generator only setup.

**Comment by aaafc** [comment] 2022-08-06 06:13
Thanks for the additional remark. Without a proper experiment with the whole model, I seem to take it for granted that the result of the overall pipeline will not presented in a greater performance gain, since I've only tried to train and evaluate Generator and ReRanker seperately, and the ReRanker itself doesn't holds a good performance for binary classification.

I'll try to perform an overall experiment of the model later on.
